2025-05-08 14:52:26,830 - root - INFO - Logging setup completed.
2025-05-08 14:52:26,830 - root - INFO - Starting GarminPlannerGUI...
2025-05-08 14:53:14,840 - root - INFO - Logging setup completed.
2025-05-08 14:53:14,840 - root - INFO - Starting GarminPlannerGUI...
2025-05-08 14:54:37,263 - root - INFO - Logging setup completed.
2025-05-08 14:54:37,263 - root - INFO - Starting GarminPlannerGUI...
2025-05-08 14:55:33,416 - root - INFO - Logging setup completed.
2025-05-08 14:55:33,417 - root - INFO - Starting GarminPlannerGUI...
2025-05-08 14:59:40,961 - root - INFO - Logging setup completed.
2025-05-08 14:59:40,962 - root - INFO - Starting GarminPlannerGUI...
2025-05-08 15:01:04,432 - root - INFO - Logging setup completed.
2025-05-08 15:01:04,432 - root - INFO - Starting GarminPlannerGUI...
2025-05-08 15:01:05,866 - root - INFO - Configuration file config.yaml not found, using defaults
2025-05-08 15:02:12,221 - root - INFO - Logging setup completed.
2025-05-08 15:02:12,222 - root - INFO - Starting GarminPlannerGUI...
2025-05-08 15:02:13,585 - root - INFO - Configuration file config.yaml not found, using defaults
2025-05-08 15:02:13,722 - root - WARNING - Session file C:\Users\f85694b/.garth\session.json not found
2025-05-08 15:05:29,262 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)'))': /sso/embed?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso
2025-05-08 15:05:30,314 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)'))': /sso/embed?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso
2025-05-08 15:05:32,366 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)'))': /sso/embed?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso
2025-05-08 15:05:32,521 - root - ERROR - Login failed: HTTPSConnectionPool(host='sso.garmin.com', port=443): Max retries exceeded with url: /sso/embed?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)')))
2025-05-08 15:06:37,685 - root - INFO - Configuration saved to config.yaml
2025-05-08 15:06:41,722 - root - INFO - Configuration saved to config.yaml
2025-05-08 15:06:47,013 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)'))': /sso/embed?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso
2025-05-08 15:06:48,068 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)'))': /sso/embed?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso
2025-05-08 15:06:50,152 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)'))': /sso/embed?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso
2025-05-08 15:06:50,372 - root - ERROR - Login failed: HTTPSConnectionPool(host='sso.garmin.com', port=443): Max retries exceeded with url: /sso/embed?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)')))
2025-05-08 15:07:27,757 - root - INFO - Logged in as jonsey2383@gmail.com
2025-05-08 15:07:28,050 - root - ERROR - Error getting user profile: Error in request: 404 Client Error: Not Found for url: https://connectapi.garmin.com/userprofile-service/userprofile
2025-05-08 15:07:49,721 - root - ERROR - Errore nel caricamento dell'allenamento: name 'get_color_for_step' is not defined
2025-05-08 15:07:53,733 - root - ERROR - Errore nel caricamento dell'allenamento: name 'get_color_for_step' is not defined
2025-05-08 15:09:15,114 - root - INFO - Configuration saved to config.yaml
2025-05-08 15:09:15,269 - root - INFO - GarminPlannerGUI terminated.
